parameters:
    sf_factory_bundle_command.executor.class: SfFactory\BundleCommandBundle\Composer\Executor
    sf_factory_bundle_command.kernel_manipulator.class: Sensio\Bundle\GeneratorBundle\Manipulator\KernelManipulator
    sf_factory_bundle_command.namespace_generator.class: SfFactory\BundleCommandBundle\AppKernel\NamespaceGenerator

services:
    sf_factory_bundle_command.executor:
        class: %sf_factory_bundle_command.executor.class%

    sf_factory_bundle_command.kernel_manipulator:
        class: %sf_factory_bundle_command.kernel_manipulator.class%
        arguments: ["@kernel"]

    sf_factory_bundle_command.namespace_generator:
        class: %sf_factory_bundle_command.namespace_generator.class%
        arguments: ["@kernel"]
